Goal 1: Predict the loan approval status (classification)

Goal 2: Predict maximum loan amount for applicants whose loan status is approved (regression)

In [1]:
import pandas as pd

In [2]:
#loading the dataset
df = pd.read_csv('/content/loan_applications_data.csv')

/tmp/ipykernel_287/1770596827.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/loan_applications_data.csv')

In [3]:
#displaying the first few instances of the data
df.head()

,id,applicant_account_No.,bank_sort_code,age,sex,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_loan_amount(allowed),credit_application_acceptance
0,717474,62012825,90025,21.0,M,Unknown,12000.0,OWN,0.0,EDUCATION,15000,6.99,0.12,N,4,Approved,-2426900,0.0
1,211588,3829308,239285,21.0,M,Unknown,13200.0,OWN,2.0,EDUCATION,25000,16.77,0.19,Y,3,Approved,-111739,0.0
2,597607,79622422,300083,23.0,M,Unknown,9600.0,RENT,5.0,MEDICAL,30000,12.42,0.31,N,3,Approved,-89000,0.0
3,684154,86043250,405179,40.0,M,Unknown,182004.0,RENT,3.0,EDUCATION,35000,8.00,0.19,N,11,Approved,35000,0.0
4,343369,73510088,300066,40.0,M,Unknown,90000.0,MORTGAGE,3.0,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,Approved,35000,0.0

In [4]:
#displaying the dimensions of the data
df.shape

(58645, 18)

In [5]:
#displaying the list of columns
list(df.columns)

['id',
 'applicant_account_No.',
 'bank_sort_code',
 'age',
 'sex',
 'education_qualifications',
 'income',
 'home_ownership',
 'employment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_loan_amount(allowed)',
 'credit_application_acceptance']

In [8]:
#displaying the type of variable data types
#checking categorical and numerical variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             58645 non-null  int64
 1   applicant_account_No.          58645 non-null  int64
 2   bank_sort_code                 58645 non-null  int64
 3   age                            58639 non-null  float64
 4   sex                            362 non-null    object
 5   education_qualifications       58645 non-null  object
 6   income                         58614 non-null  float64
 7   home_ownership                 58645 non-null  object
 8   employment_length              58630 non-null  float64
 9   loan_intent                    58645 non-null  object
 10  loan_amount                    58645 non-null  int64
 11  loan_interest_rate             58635 non-null  float64
 12  loan_income_ratio              58645 non-null  float64
 13  payment_default_on_file        58640 non-null  object
 14  credit_history_length          58645 non-null  int64
 15  loan_approval_status           58644 non-null  object
 16  max_loan_amount(allowed)       58645 non-null  int64
 17  credit_application_acceptance  58644 non-null  float64
dtypes: float64(6), int64(6), object(6)
memory usage: 8.1+ MB

In [9]:
#basic descriptive statistics
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,58645.0,5.494166e+05,2.600044e+05,100006.00,324881.00,548673.00,773531.00,9.999960e+05
applicant_account_No.,58645.0,5.055471e+07,2.864283e+07,1000384.00,25731092.00,50576780.00,75393934.00,9.999746e+07
bank_sort_code,58645.0,3.537375e+05,2.275277e+05,10004.00,165810.00,301495.00,600168.00,9.800000e+05
age,58639.0,2.755504e+01,6.099005e+00,-30.00,23.00,26.00,30.00,1.800000e+02
income,58614.0,6.405295e+04,3.793834e+04,4200.00,42000.00,58000.00,75662.00,1.900000e+06
employment_length,58630.0,4.702746e+00,3.999875e+00,0.00,2.00,4.00,7.00,1.500000e+02
loan_amount,58645.0,9.217557e+03,5.563807e+03,500.00,5000.00,8000.00,12000.00,3.500000e+04
loan_interest_rate,58635.0,1.068922e+01,3.257150e+00,-11.14,7.88,10.75,12.99,2.000000e+02
loan_income_ratio,58645.0,1.592375e-01,9.169179e-02,0.00,0.09,0.14,0.21,8.300000e-01
credit_history_length,58645.0,5.813062e+00,4.027495e+00,2.00,3.00,4.00,8.00,3.000000e+01
max_loan_amount(allowed),58645.0,2.823538e+05,5.148478e+07,-2426900.00,38003.00,62392.00,92716.00,1.246799e+10
credit_application_acceptance,58644.0,1.423846e-01,3.494471e-01,0.00,0.00,0.00,0.00,1.000000e+00

In [10]:
df.describe(include='all').transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,58645.0,NaN,NaN,NaN,549416.624537,260004.378682,100006.0,324881.0,548673.0,773531.0,999996.0
applicant_account_No.,58645.0,NaN,NaN,NaN,50554713.701458,28642831.407046,1000384.0,25731092.0,50576780.0,75393934.0,99997465.0
bank_sort_code,58645.0,NaN,NaN,NaN,353737.500077,227527.682002,10004.0,165810.0,301495.0,600168.0,980000.0
age,58639.0,NaN,NaN,NaN,27.55504,6.099005,-30.0,23.0,26.0,30.0,180.0
sex,362,4,M,126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education_qualifications,58645,6,Unknown,58303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
income,58614.0,NaN,NaN,NaN,64052.94933,37938.336326,4200.0,42000.0,58000.0,75662.0,1900000.0
home_ownership,58645,4,RENT,30594,NaN,NaN,NaN,NaN,NaN,NaN,NaN
employment_length,58630.0,NaN,NaN,NaN,4.702746,3.999875,0.0,2.0,4.0,7.0,150.0
loan_intent,58645,6,EDUCATION,12271,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amount,58645.0,NaN,NaN,NaN,9217.556518,5563.807384,500.0,5000.0,8000.0,12000.0,35000.0
loan_interest_rate,58635.0,NaN,NaN,NaN,10.689216,3.25715,-11.14,7.88,10.75,12.99,200.0
loan_income_ratio,58645.0,NaN,NaN,NaN,0.159238,0.091692,0.0,0.09,0.14,0.21,0.83
payment_default_on_file,58640,4,N,49933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
credit_history_length,58645.0,NaN,NaN,NaN,5.813062,4.027495,2.0,3.0,4.0,8.0,30.0
loan_approval_status,58644,8,Approved,50210,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max_loan_amount(allowed),58645.0,NaN,NaN,NaN,282353.842715,51484775.196066,-2426900.0,38003.0,62392.0,92716.0,12467989660.0
credit_application_acceptance,58644.0,NaN,NaN,NaN,0.142385,0.349447,0.0,0.0,0.0,0.0,1.0

In [11]:
#missing data values
df.isnull().sum()

id                                   0
applicant_account_No.                0
bank_sort_code                       0
age                                  6
sex                              58283
education_qualifications             0
income                              31
home_ownership                       0
employment_length                   15
loan_intent                          0
loan_amount                          0
loan_interest_rate                  10
loan_income_ratio                    0
payment_default_on_file              5
credit_history_length                0
loan_approval_status                 1
max_loan_amount(allowed)             0
credit_application_acceptance        1
dtype: int64

In [12]:
#displaying portion of missing data
df.isnull().sum()/len(df) * 100

id                                0.000000
applicant_account_No.             0.000000
bank_sort_code                    0.000000
age                               0.010231
sex                              99.382727
education_qualifications          0.000000
income                            0.052860
home_ownership                    0.000000
employment_length                 0.025578
loan_intent                       0.000000
loan_amount                       0.000000
loan_interest_rate                0.017052
loan_income_ratio                 0.000000
payment_default_on_file           0.008526
credit_history_length             0.000000
loan_approval_status              0.001705
max_loan_amount(allowed)          0.000000
credit_application_acceptance     0.001705
dtype: float64